/**
 * Canonical error codes used across the PCP API.
 *
 * Goals:
 * - avoid ad-hoc strings scattered through handlers
 * - keep a stable contract for the frontend (and tests)
 * - make it easy to search / refactor
 *
 * NOTE:
 * We keep codes as SCREAMING_SNAKE_CASE strings because they are already used in logs/tests.
 */
export const ErrorCode = {
  // Generic / platform
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  PAYLOAD_INVALID: "PAYLOAD_INVALID",
  RATE_LIMITED: "RATE_LIMITED",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  VOLUNTEER_RATE_LIMITED: "VOLUNTEER_RATE_LIMITED",

  // Auth
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_DISABLED: "AUTH_REFRESH_DISABLED",
  AUTH_CSRF_MISSING: "AUTH_CSRF_MISSING",
  AUTH_CSRF_INVALID: "AUTH_CSRF_INVALID",
  AUTH_SIGNOUT_REFRESH_MISSING: "AUTH_SIGNOUT_REFRESH_MISSING",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AUTH_SIGNUP_VALIDATION_FAILED: "AUTH_SIGNUP_VALIDATION_FAILED",
  AUTH_SIGNIN_VALIDATION_FAILED: "AUTH_SIGNIN_VALIDATION_FAILED",

  // Volunteers
  VOLUNTEER_VALIDATION_FAILED: "VOLUNTEER_VALIDATION_FAILED",
  VOLUNTEER_EMAIL_EXISTS: "VOLUNTEER_EMAIL_EXISTS",
  VOLUNTEER_ACCOUNT_EXISTS: "VOLUNTEER_ACCOUNT_EXISTS",
  VOLUNTEER_CAPTCHA_REQUIRED: "VOLUNTEER_CAPTCHA_REQUIRED",
  VOLUNTEER_CAPTCHA_INVALID: "VOLUNTEER_CAPTCHA_INVALID",
  VOLUNTEER_CAPTCHA_UNAVAILABLE: "VOLUNTEER_CAPTCHA_UNAVAILABLE",
  VOLUNTEER_ID_INVALID: "VOLUNTEER_ID_INVALID",
  VOLUNTEER_NOT_FOUND: "VOLUNTEER_NOT_FOUND",
  VOLUNTEER_INVALID_COUNTY: "VOLUNTEER_INVALID_COUNTY",
  VOLUNTEER_OWNER_INVALID: "VOLUNTEER_OWNER_INVALID",
  VOLUNTEER_WORKFLOW_VALIDATION_FAILED: "VOLUNTEER_WORKFLOW_VALIDATION_FAILED",
  VOLUNTEER_BULK_DELETE_VALIDATION_FAILED: "VOLUNTEER_BULK_DELETE_VALIDATION_FAILED",
  VOLUNTEERS_CURSOR_INVALID: "VOLUNTEERS_CURSOR_INVALID",
  ADMIN_AUDIT_CURSOR_INVALID: "ADMIN_AUDIT_CURSOR_INVALID",

  // News
  NEWS_ID_INVALID: "NEWS_ID_INVALID",
  NEWS_NOT_FOUND: "NEWS_NOT_FOUND",
  NEWS_CURSOR_INVALID: "NEWS_CURSOR_INVALID",
  NEWS_ADMIN_CURSOR_INVALID: "NEWS_ADMIN_CURSOR_INVALID",
  NEWS_CREATE_VALIDATION_FAILED: "NEWS_CREATE_VALIDATION_FAILED",
  NEWS_UPDATE_VALIDATION_FAILED: "NEWS_UPDATE_VALIDATION_FAILED",

  // News media
  NEWS_MEDIA_FILE_MISSING: "NEWS_MEDIA_FILE_MISSING",
  NEWS_MEDIA_FILE_TOO_LARGE: "NEWS_MEDIA_FILE_TOO_LARGE",
  NEWS_MEDIA_TYPE_INVALID: "NEWS_MEDIA_TYPE_INVALID",
  NEWS_MEDIA_CONTENT_INVALID: "NEWS_MEDIA_CONTENT_INVALID",
  NEWS_MEDIA_TYPE_MISMATCH: "NEWS_MEDIA_TYPE_MISMATCH",
  NEWS_MEDIA_EXTENSION_MISSING: "NEWS_MEDIA_EXTENSION_MISSING",
  NEWS_MEDIA_EXTENSION_INVALID: "NEWS_MEDIA_EXTENSION_INVALID",
  NEWS_MEDIA_SCAN_TIMEOUT: "NEWS_MEDIA_SCAN_TIMEOUT",
  NEWS_MEDIA_SCAN_FAILED: "NEWS_MEDIA_SCAN_FAILED",
  NEWS_MEDIA_INFECTED: "NEWS_MEDIA_INFECTED",
  NEWS_MEDIA_ASSET_ID_INVALID: "NEWS_MEDIA_ASSET_ID_INVALID",
  NEWS_MEDIA_ASSET_NOT_FOUND: "NEWS_MEDIA_ASSET_NOT_FOUND",
  NEWS_MEDIA_ASSET_IN_USE: "NEWS_MEDIA_ASSET_IN_USE",
  NEWS_MEDIA_DELETE_FAILED: "NEWS_MEDIA_DELETE_FAILED",
  NEWS_MEDIA_UPLOAD_INVALID: "NEWS_MEDIA_UPLOAD_INVALID",

  // Members / orgs / finance / elections
  MEMBERS_QUERY_INVALID: "MEMBERS_QUERY_INVALID",
  ORGANIZATIONS_QUERY_INVALID: "ORGANIZATIONS_QUERY_INVALID",
  FINANCE_QUERY_INVALID: "FINANCE_QUERY_INVALID",
  ELECTIONS_QUERY_INVALID: "ELECTIONS_QUERY_INVALID",

  // Admin notifications
  EMAIL_TEST_VALIDATION_FAILED: "EMAIL_TEST_VALIDATION_FAILED",
  EMAIL_TEST_RECIPIENT_MISSING: "EMAIL_TEST_RECIPIENT_MISSING",
  EMAIL_TEST_SEND_FAILED: "EMAIL_TEST_SEND_FAILED",
  EMAIL_NOTIFICATIONS_DISABLED: "EMAIL_NOTIFICATIONS_DISABLED",

  // Storage
  MEDIA_STORAGE_PATH_INVALID: "MEDIA_STORAGE_PATH_INVALID",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
