/**
 * Canonical error codes used across the PCS API.
 *
 * Goals:
 * - avoid ad-hoc strings scattered through handlers
 * - keep a stable contract for the frontend (and tests)
 * - make it easy to search / refactor
 *
 * NOTE:
 * We keep codes as SCREAMING_SNAKE_CASE strings because they are already used in logs/tests.
 */
export const ErrorCode = {
  // Generic / platform
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  EXECUTIVE_EXPIRATION_CONFLICT: "EXECUTIVE_EXPIRATION_CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  PAYLOAD_INVALID: "PAYLOAD_INVALID",
  RATE_LIMITED: "RATE_LIMITED",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  VOLUNTEER_RATE_LIMITED: "VOLUNTEER_RATE_LIMITED",

  // Auth
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  ADMIN_PERMISSION_REQUIRED: "ADMIN_PERMISSION_REQUIRED",
  ADMIN_TERRITORY_REQUIRED: "ADMIN_TERRITORY_REQUIRED",
  ADMIN_TERRITORY_FORBIDDEN: "ADMIN_TERRITORY_FORBIDDEN",
  ADMIN_NATIONAL_SCOPE_REQUIRED: "ADMIN_NATIONAL_SCOPE_REQUIRED",
  AUTH_REFRESH_DISABLED: "AUTH_REFRESH_DISABLED",
  AUTH_CSRF_MISSING: "AUTH_CSRF_MISSING",
  AUTH_CSRF_INVALID: "AUTH_CSRF_INVALID",
  AUTH_SIGNOUT_REFRESH_MISSING: "AUTH_SIGNOUT_REFRESH_MISSING",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AUTH_SIGNUP_VALIDATION_FAILED: "AUTH_SIGNUP_VALIDATION_FAILED",
  AUTH_SIGNIN_VALIDATION_FAILED: "AUTH_SIGNIN_VALIDATION_FAILED",

  // Volunteers
  VOLUNTEER_VALIDATION_FAILED: "VOLUNTEER_VALIDATION_FAILED",
  VOLUNTEER_EMAIL_EXISTS: "VOLUNTEER_EMAIL_EXISTS",
  VOLUNTEER_ACCOUNT_EXISTS: "VOLUNTEER_ACCOUNT_EXISTS",
  VOLUNTEER_ID_INVALID: "VOLUNTEER_ID_INVALID",
  VOLUNTEER_NOT_FOUND: "VOLUNTEER_NOT_FOUND",
  VOLUNTEER_INVALID_COUNTY: "VOLUNTEER_INVALID_COUNTY",
  VOLUNTEER_OWNER_INVALID: "VOLUNTEER_OWNER_INVALID",
  VOLUNTEER_WORKFLOW_VALIDATION_FAILED: "VOLUNTEER_WORKFLOW_VALIDATION_FAILED",
  VOLUNTEER_BULK_DELETE_VALIDATION_FAILED: "VOLUNTEER_BULK_DELETE_VALIDATION_FAILED",
  VOLUNTEERS_CURSOR_INVALID: "VOLUNTEERS_CURSOR_INVALID",
  ADMIN_AUDIT_CURSOR_INVALID: "ADMIN_AUDIT_CURSOR_INVALID",

  // Mobilization
  MOBILIZATION_VALIDATION_FAILED: "MOBILIZATION_VALIDATION_FAILED",
  MOBILIZATION_ACTION_NOT_FOUND: "MOBILIZATION_ACTION_NOT_FOUND",
  MOBILIZATION_ACTION_FULL: "MOBILIZATION_ACTION_FULL",
  MOBILIZATION_RESPONSE_EXISTS: "MOBILIZATION_RESPONSE_EXISTS",
  POLITICAL_OPERATION_INVALID: "POLITICAL_OPERATION_INVALID",
  POLITICAL_OPERATION_NOT_FOUND: "POLITICAL_OPERATION_NOT_FOUND",
  POLITICAL_OPERATION_VERSION_CONFLICT: "POLITICAL_OPERATION_VERSION_CONFLICT",
  POLITICAL_PARTICIPANT_NOT_FOUND: "POLITICAL_PARTICIPANT_NOT_FOUND",
  POLITICAL_PARTICIPANT_INVALID: "POLITICAL_PARTICIPANT_INVALID",
  COMMUNICATION_AUDIENCE_INVALID: "COMMUNICATION_AUDIENCE_INVALID",
  COMMUNICATION_AUDIENCE_EMPTY: "COMMUNICATION_AUDIENCE_EMPTY",
  MEMBER_PORTAL_MEMBERSHIP_NOT_FOUND: "MEMBER_PORTAL_MEMBERSHIP_NOT_FOUND",
  MEMBER_PORTAL_ACTION_FORBIDDEN: "MEMBER_PORTAL_ACTION_FORBIDDEN",

  // News
  NEWS_ID_INVALID: "NEWS_ID_INVALID",
  NEWS_NOT_FOUND: "NEWS_NOT_FOUND",
  NEWS_CURSOR_INVALID: "NEWS_CURSOR_INVALID",
  NEWS_ADMIN_CURSOR_INVALID: "NEWS_ADMIN_CURSOR_INVALID",
  NEWS_CREATE_VALIDATION_FAILED: "NEWS_CREATE_VALIDATION_FAILED",
  NEWS_UPDATE_VALIDATION_FAILED: "NEWS_UPDATE_VALIDATION_FAILED",

  // News media
  NEWS_MEDIA_FILE_MISSING: "NEWS_MEDIA_FILE_MISSING",
  NEWS_MEDIA_FILE_TOO_LARGE: "NEWS_MEDIA_FILE_TOO_LARGE",
  NEWS_MEDIA_TYPE_INVALID: "NEWS_MEDIA_TYPE_INVALID",
  NEWS_MEDIA_CONTENT_INVALID: "NEWS_MEDIA_CONTENT_INVALID",
  NEWS_MEDIA_TYPE_MISMATCH: "NEWS_MEDIA_TYPE_MISMATCH",
  NEWS_MEDIA_EXTENSION_MISSING: "NEWS_MEDIA_EXTENSION_MISSING",
  NEWS_MEDIA_EXTENSION_INVALID: "NEWS_MEDIA_EXTENSION_INVALID",
  NEWS_MEDIA_SCAN_TIMEOUT: "NEWS_MEDIA_SCAN_TIMEOUT",
  NEWS_MEDIA_SCAN_FAILED: "NEWS_MEDIA_SCAN_FAILED",
  NEWS_MEDIA_INFECTED: "NEWS_MEDIA_INFECTED",
  NEWS_MEDIA_ASSET_ID_INVALID: "NEWS_MEDIA_ASSET_ID_INVALID",
  NEWS_MEDIA_ASSET_NOT_FOUND: "NEWS_MEDIA_ASSET_NOT_FOUND",
  NEWS_MEDIA_ASSET_IN_USE: "NEWS_MEDIA_ASSET_IN_USE",
  NEWS_MEDIA_DELETE_FAILED: "NEWS_MEDIA_DELETE_FAILED",
  NEWS_MEDIA_UPLOAD_INVALID: "NEWS_MEDIA_UPLOAD_INVALID",

  // Members / orgs / finance / elections
  MEMBERS_QUERY_INVALID: "MEMBERS_QUERY_INVALID",
  MEMBERSHIP_ID_INVALID: "MEMBERSHIP_ID_INVALID",
  MEMBERSHIP_ACTION_INVALID: "MEMBERSHIP_ACTION_INVALID",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  MEMBERSHIP_TRANSITION_INVALID: "MEMBERSHIP_TRANSITION_INVALID",
  MEMBERSHIP_VERSION_CONFLICT: "MEMBERSHIP_VERSION_CONFLICT",
  MEMBERSHIP_SELF_ACTION_FORBIDDEN: "MEMBERSHIP_SELF_ACTION_FORBIDDEN",
  MEMBERSHIP_LEADERSHIP_ACTION_FORBIDDEN: "MEMBERSHIP_LEADERSHIP_ACTION_FORBIDDEN",
  MEMBERSHIP_ORGANIZATION_INVALID: "MEMBERSHIP_ORGANIZATION_INVALID",
  MEMBERSHIP_APPROVAL_ORGANIZATION_INVALID: "MEMBERSHIP_APPROVAL_ORGANIZATION_INVALID",
  MEMBERSHIP_TRANSFER_SAME_ORGANIZATION: "MEMBERSHIP_TRANSFER_SAME_ORGANIZATION",
  ORGANIZATIONS_QUERY_INVALID: "ORGANIZATIONS_QUERY_INVALID",
  ORGANIZATION_VALIDATION_FAILED: "ORGANIZATION_VALIDATION_FAILED",
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_CONFLICT: "ORGANIZATION_CONFLICT",
  ORGANIZATION_MANDATE_NOT_FOUND: "ORGANIZATION_MANDATE_NOT_FOUND",
  ORGANIZATION_OBJECTIVE_NOT_FOUND: "ORGANIZATION_OBJECTIVE_NOT_FOUND",
  ORGANIZATION_MANDATE_DECISION_CONFLICT: "ORGANIZATION_MANDATE_DECISION_CONFLICT",
  ORGANIZATION_MANDATE_CONFLICT: "ORGANIZATION_MANDATE_CONFLICT",
  FINANCE_QUERY_INVALID: "FINANCE_QUERY_INVALID",
  ELECTIONS_QUERY_INVALID: "ELECTIONS_QUERY_INVALID",
  GOVERNANCE_JOURNAL_QUERY_INVALID: "GOVERNANCE_JOURNAL_QUERY_INVALID",
  CONGRESS_INVALID: "CONGRESS_INVALID",
  CONGRESS_NOT_FOUND: "CONGRESS_NOT_FOUND",
  CONGRESS_TRANSITION_INVALID: "CONGRESS_TRANSITION_INVALID",
  CONGRESS_QUORUM_NOT_REACHED: "CONGRESS_QUORUM_NOT_REACHED",
  CONGRESS_DELEGATE_NOT_FOUND: "CONGRESS_DELEGATE_NOT_FOUND",
  CONGRESS_CANDIDACY_NOT_FOUND: "CONGRESS_CANDIDACY_NOT_FOUND",
  CONGRESS_VOTE_INVALID: "CONGRESS_VOTE_INVALID",
  ARBITRATION_INVALID: "ARBITRATION_INVALID",
  ARBITRATION_NOT_FOUND: "ARBITRATION_NOT_FOUND",
  ARBITRATION_CONFLICT: "ARBITRATION_CONFLICT",
  ARBITRATION_INCOMPATIBLE: "ARBITRATION_INCOMPATIBLE",
  ARBITRATION_PROCEDURE_INVALID: "ARBITRATION_PROCEDURE_INVALID",
  EXECUTIVE_TARGET_INVALID: "EXECUTIVE_TARGET_INVALID",
  EXECUTIVE_TARGET_NOT_FOUND: "EXECUTIVE_TARGET_NOT_FOUND",

  // Admin notifications
  EMAIL_TEST_VALIDATION_FAILED: "EMAIL_TEST_VALIDATION_FAILED",
  EMAIL_TEST_RECIPIENT_MISSING: "EMAIL_TEST_RECIPIENT_MISSING",
  EMAIL_TEST_SEND_FAILED: "EMAIL_TEST_SEND_FAILED",
  EMAIL_NOTIFICATIONS_DISABLED: "EMAIL_NOTIFICATIONS_DISABLED",

  // Storage
  MEDIA_STORAGE_PATH_INVALID: "MEDIA_STORAGE_PATH_INVALID",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
